

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
packageExtensions:
  webpack@*:
    dependencies:
      lodash: "^4.15.0"
    peerDependencies:
      webpack-cli: "*"
    peerDependenciesMeta:
      webpack-cli:
        optional: true

  eslint-config-react-app@*:
    dependencies:
      '@babel/plugin-transform-react-jsx': "^7.14.9"